name: Hourly Data Update

on:
  schedule:
    - cron: '0 * * * *' # Her saatin başında (13:00, 14:00 vb.) otomatik çalışır
  workflow_dispatch: # İstediğinde manuel çalıştırmak için buton ekler
  
jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosyaları depona geri yazabilmesi için şart
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Projects and Games
        run: |
          # Projeleri çek (Hata almamak için -L yönlendirmesini ekledik)
          curl -sL "https://api.github.com/repos/cemal201138/My_Netlify_SitesApps/contents/" > projects.json
          # Oyunları çek
          curl -sL "https://api.github.com/repos/cemal201138-file-user/games/releases" > games.json
          # dosyaları Çek
          curl -sL "https://api.github.com/repos/cemal201138-file-user/files/releases" > files.json
          

      - name: Commit and Push Changes
        run: |
          # Senin kimlik bilgilerinle yapılandırma
          git config --local user.name "cemal201138"
          git config --local user.email "cemal201138@users.noreply.github.com"
          git add projects.json games.json files.json
          # Sadece değişiklik varsa commit at, yoksa hata verme
          git diff --quiet && git diff --staged --quiet || (git commit -m "Hourly auto-update: $(date)" && git push)
